server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  application:
    name: be16-ordersystem

  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3309/ordersystem
    username: xxxxx
    password: yyyyy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  servlet:
    multipart:
      # spring의 디폴트 사이즈 10MB
      max-file-size: 1000MB
      max-request-size: 1000MB

# aws s3 접근 설정
cloud:
  aws:
    credentials:
      access-key: xx
      secret-key: yy
    region:
      static: ap-northeast-2
  s3:
    bucket: crongs-order

jwt:
  expirationAt: 1000
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY2V0a2V5Cg==
  expirationRt: 10000
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY2V0a2V5Cg==